import assert from 'node:assert/strict';
import { environment, engine, protocol } from './test_helpers.mjs';
import { arrangeExercises, sequenceConflict } from './src/core/ExerciseOrder.js';
import { ExerciseReorder } from './src/ui/ExerciseReorder.js';

const chest = { primary: 'chest', muscles: ['chest', 'triceps'] };
const legs = { primary: 'quads', muscles: ['quads'] };
assert.deepEqual(arrangeExercises([0, 1, 2], 2, 0, new Set(), [chest, legs, chest]), [2, 1, 0]);
assert.deepEqual(arrangeExercises([0, 1, 2, 3], 2, 1, new Set(), [chest, legs, chest, legs]), [1, 2, 3, 0], 'Separation takes precedence over an unmoved priority opener');
assert.ok(sequenceConflict(chest, { primary: 'shoulders', muscles: ['shoulders', 'triceps'] }) > 0);
assert.equal(arrangeExercises([0, 1, 2], 2, 1, new Set([1]), [chest, legs, chest]), null);
assert.deepEqual(arrangeExercises([0, 1, 2], 2, 0, new Set(), [chest, chest, chest]), [2, 0, 1]);
for (const ex of Object.values(protocol.exercise_library)) {
    assert.ok(ex.sequencing.muscles.includes(ex.sequencing.primary));
}
environment();
let a = await engine();
const original = a.getExerciseOrder(0);
await a.logSet(a.protocolData[0].exercises[0]._exerciseId, 20, 8, 8);
await a.swapExercise(0, 1, 'LEG_PRESS');
assert.equal(await a.reorderExercise(0, 2, 0), true);
const changed = a.getExerciseOrder(0);
assert.equal(changed[0], 2);
assert.notEqual(changed[1], 0, 'Chest exercises stay separated');
assert.equal(a.protocolData[0].exercises[1]._exerciseId, 'LEG_PRESS');
assert.equal(a.getExerciseLogs(a.protocolData[0].exercises[0]._exerciseId).length, 1);
a = await engine();
assert.deepEqual(a.getExerciseOrder(0), changed, 'Reload retains order');
assert.equal(await a.undoExerciseOrder(0), true);
assert.deepEqual(a.getExerciseOrder(0), original);
assert.equal(await a.reorderExercise(0, 2, 0), true);
await a.toggleComplete('ex-0-1', 0);
const lockedPosition = a.getExerciseOrder(0).indexOf(1);
assert.equal(await a.reorderExercise(0, 1, 0), false);
assert.equal(await a.reorderExercise(0, 4, lockedPosition), false);
assert.equal(await a.reorderExercise(0, 4, 0), true);
assert.equal(a.getExerciseOrder(0).indexOf(1), lockedPosition);
assert.equal(a.state.done[0]['ex-0-1'], true);
const b = await engine();
await b.toggleComplete('ex-0-3', 0);
await a.reorderExercise(0, 5, 0);
assert.equal(a.state.done[0]['ex-0-3'], true, 'Concurrent checks survive');
const actual = a.getExerciseOrder(0);
await a.finishSession();
assert.deepEqual(a.getDaySummary(0).order, actual);
assert.equal(await a.reorderExercise(0, 2, 0), false);
await a.reopenLastDay();
assert.deepEqual(a.getExerciseOrder(0), actual);
for (let day = 0; day < 4; day++) { await a.setDay(day); await a.finishSession(); }
assert.deepEqual(a.getExerciseOrder(0), original, 'New cycle restores prescribed order');
await a.reopenLastDay();
assert.deepEqual(a.getExerciseOrder(0), actual, 'Cycle undo restores prior session orders');
environment(); a = await engine();
const mutate = a.storage.mutateWorkout.bind(a.storage);
a.storage.mutateWorkout = reducer => mutate((...args) => { reducer(...args); throw new Error('Injected reorder failure'); });
assert.equal(await a.reorderExercise(0, 2, 0), false);
assert.deepEqual(a.getExerciseOrder(0), original, 'Failed save leaves order intact');
assert.equal(await a.reorderExercise(0, 2, NaN), false);
// Exercise the actual pointer boundary, including hold, drop and cancellation.
const realTimer = globalThis.setTimeout;
let held;
globalThis.setTimeout = callback => { held = callback; return 1; };
globalThis.requestAnimationFrame = () => 1;
globalThis.cancelAnimationFrame = () => {};
const surface = new EventTarget();
surface.querySelectorAll = () => [];
surface.querySelector = () => null;
let captured = false;
const card = { dataset: { idx: '2' }, classList: { add() {} }, querySelector: () => ({ style: {} }) };
const handle = { closest: () => card, setPointerCapture() { captured = true; }, hasPointerCapture() { return captured; }, releasePointerCapture() { captured = false; } };
const target = { closest: selector => selector === '.reorder-handle' ? handle : null };
const calls = [];
const stubEngine = { state: { day: 0 }, cycleId: 'test-cycle', reorderExercise: async (...args) => { calls.push(args); return true; } };
const gestures = new ExerciseReorder(surface, stubEngine, () => {});
function pointer(type, y) {
    const event = new Event(type);
    Object.assign(event, { button: 0, pointerId: 1, clientY: y });
    Object.defineProperty(event, 'target', { value: target });
    surface.dispatchEvent(event);
}
pointer('pointerdown', 100); held();
assert.equal(gestures.drag.active, true);
gestures.destination = 0;
pointer('pointermove', 50); pointer('pointerup', 50);
await Promise.resolve();
assert.deepEqual(calls, [[0, 2, 0]]);
assert.equal(captured, false);
pointer('pointerdown', 100); pointer('pointermove', 120);
assert.equal(gestures.drag, null, 'Movement before the hold cancels pickup');
pointer('pointerdown', 100); held(); pointer('pointercancel', 100);
assert.equal(gestures.drag, null);
assert.equal(calls.length, 1, 'Cancellation does not save a move');
globalThis.setTimeout = realTimer;
console.log('Exercise ordering tests passed');
